# Changes here will be overwritten by Copier
_commit: v0.9.0
_src_path: https://github.com/fohte/generic-boilerplate
description:
  "@fohte's personal hub for receiving GitHub webhooks and dispatching
  to handlers"
is_public: true
is_web_app: true
project_name: webhook-hub
repo_language: en
subpackages: []
type: node
use_release_please: false
use_storybook: false
web_app_port: 8080
