issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/webhook-hub@1263108494:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/webhook-hub/\.github/workflows/test\.yml@[^@]+$
permissions:
  contents: write
